//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusLifePlanner.Infra.IoC.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CampusLifePlanner.Infra.IoC.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        public static string EVENT_PAGE_LBL__DESCRIPTON {
            get {
                return ResourceManager.GetString("EVENT_PAGE_LBL__DESCRIPTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while fetching events.
        /// </summary>
        public static string EX_MSG_AN_ERROR_OCCORRED_FETCHING_EVENT {
            get {
                return ResourceManager.GetString("EX_MSG_AN_ERROR_OCCORRED_FETCHING_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} cannot be null.
        /// </summary>
        public static string EX_MSG_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("EX_MSG_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while creating the {0}. Try again..
        /// </summary>
        public static string EX_MSG_CREATE_ERROR {
            get {
                return ResourceManager.GetString("EX_MSG_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The start date cannot be greater than the end date.
        /// </summary>
        public static string EX_MSG_DATE_START_END_INVALID {
            get {
                return ResourceManager.GetString("EX_MSG_DATE_START_END_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The start time cannot be the same as the end time..
        /// </summary>
        public static string EX_MSG_DATE_START_END_INVALID_SAME_TIME {
            get {
                return ResourceManager.GetString("EX_MSG_DATE_START_END_INVALID_SAME_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are registered events for this course.
        /// </summary>
        public static string EX_MSG_EVENTS_REGISTERED_FOR_THIS_COURSE {
            get {
                return ResourceManager.GetString("EX_MSG_EVENTS_REGISTERED_FOR_THIS_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} or {1} invalid.
        /// </summary>
        public static string EX_MSG_INVALID_USER {
            get {
                return ResourceManager.GetString("EX_MSG_INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in all mandatory fields. The title and location must contain at least 3 characters..
        /// </summary>
        public static string EX_MSG_MODEL_INVALID {
            get {
                return ResourceManager.GetString("EX_MSG_MODEL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not found in database.
        /// </summary>
        public static string EX_MSG_NOT_FOUND_DATABASE {
            get {
                return ResourceManager.GetString("EX_MSG_NOT_FOUND_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in all fields, please..
        /// </summary>
        public static string EX_MSG_NULL_ERROR {
            get {
                return ResourceManager.GetString("EX_MSG_NULL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email is already registered..
        /// </summary>
        public static string EX_MSG_USER_EXIST {
            get {
                return ResourceManager.GetString("EX_MSG_USER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is not enrolled in any course.
        /// </summary>
        public static string EX_MSG_USER_NOT_ENROLLMENT_COURSE {
            get {
                return ResourceManager.GetString("EX_MSG_USER_NOT_ENROLLMENT_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not found.
        /// </summary>
        public static string EX_MSG_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("EX_MSG_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EduPlaner is your tool to maximize academic success! With an innovative approach, our app allows students to access and view their activities and assignments related to each course. Simplifying academic management, EduPlaner helps you stay in control of your studies, ensuring that no important deadlines are missed. Experience the efficiency of an activity manager designed to enhance your educational experience. Discover the power of organization with EduPlaner!.
        /// </summary>
        public static string GENERAL_MSG_DESCRIPTION_PROJECT {
            get {
                return ResourceManager.GetString("GENERAL_MSG_DESCRIPTION_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To stay up to date with events and activities, please choose the course in which you are currently enrolled. This will allow you to keep track of all relevant information and participate in scheduled activities. we are here for ensure that you are always well informed and engaged in your course..
        /// </summary>
        public static string GENERAL_MSG_HOME_ENROLLMENT {
            get {
                return ResourceManager.GetString("GENERAL_MSG_HOME_ENROLLMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        public static string GENERAL_PAGE_BTN_ADD {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detail.
        /// </summary>
        public static string GENERAL_PAGE_BTN_DETAIL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        public static string GENERAL_PAGE_BTN_EDIT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enrollment.
        /// </summary>
        public static string GENERAL_PAGE_BTN_ENROLLMENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_ENROLLMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        public static string GENERAL_PAGE_BTN_SAVE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shared.
        /// </summary>
        public static string GENERAL_PAGE_BTN_SHARED {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Image perfil.
        /// </summary>
        public static string GENERAL_PAGE_IMAGE_PERFIL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_IMAGE_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CANCEL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Changes.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CHANGES {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose your course.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CHOOSE_COURSE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CHOOSE_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CLOSE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course.
        /// </summary>
        public static string GENERAL_PAGE_LBL_COURSE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        public static string GENERAL_PAGE_LBL_DELETE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you really want to delete this?.
        /// </summary>
        public static string GENERAL_PAGE_LBL_DELETE_THIS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_DELETE_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        public static string GENERAL_PAGE_LBL_EVENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Events.
        /// </summary>
        public static string GENERAL_PAGE_LBL_EVENTS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No {0} found, enjoy your day!.
        /// </summary>
        public static string GENERAL_PAGE_LBL_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        public static string GENERAL_PAGE_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove.
        /// </summary>
        public static string GENERAL_PAGE_LBL_REMOVE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shared event.
        /// </summary>
        public static string GENERAL_PAGE_LBL_SHARED_EVENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_SHARED_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to the.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TO_THE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TO_THE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Today.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TODAY {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tomorrow.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TOMORROW {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TOMORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User.
        /// </summary>
        public static string GENERAL_PAGE_LBL_USER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a In.
        /// </summary>
        public static string GENERAL_PAGE_LINK_IN {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LINK_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Other.
        /// </summary>
        public static string GENERAL_PAGE_LINK_OTHER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LINK_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [0} created success.
        /// </summary>
        public static string GENERAL_PAGE_MSG__CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG__CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} deleted success.
        /// </summary>
        public static string GENERAL_PAGE_MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} update success.
        /// </summary>
        public static string GENERAL_PAGE_MSG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EduPlaner - Organizing Your Academic Success.
        /// </summary>
        public static string GENERAL_PAGE_TITLE_PROJECT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_TITLE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Welcome to EduPlaner.
        /// </summary>
        public static string GENERAL_PAGE_WELCOME_EDU_PLANER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_WELCOME_EDU_PLANER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identifier.
        /// </summary>
        public static string GENERAL_PRT_LBL_ID {
            get {
                return ResourceManager.GetString("GENERAL_PRT_LBL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To stay up to date with events and activities, please choose the course in which you are currently enrolled. This will allow you to keep track of all relevant information and participate in scheduled activities. we are here for ensure that you are always well informed and engaged in your course..
        /// </summary>
        public static string MSG_PAGE_ENROLLMENT_COURSE {
            get {
                return ResourceManager.GetString("MSG_PAGE_ENROLLMENT_COURSE", resourceCulture);
            }
        }
    }
}
