//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusLifePlanner.Infra.IoC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CampusLifePlanner.Infra.IoC.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EVENT_PAGE_LBL__DESCRIPTON {
            get {
                return ResourceManager.GetString("EVENT_PAGE_LBL__DESCRIPTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching events.
        /// </summary>
        public static string EX_MSG_AN_ERROR_OCCORRED_FETCHING_EVENT {
            get {
                return ResourceManager.GetString("EX_MSG_AN_ERROR_OCCORRED_FETCHING_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null.
        /// </summary>
        public static string EX_MSG_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("EX_MSG_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the {0}. Try again..
        /// </summary>
        public static string EX_MSG_CREATE_ERROR {
            get {
                return ResourceManager.GetString("EX_MSG_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date cannot be greater than the end date.
        /// </summary>
        public static string EX_MSG_DATE_START_END_INVALID {
            get {
                return ResourceManager.GetString("EX_MSG_DATE_START_END_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time cannot be the same as the end time..
        /// </summary>
        public static string EX_MSG_DATE_START_END_INVALID_SAME_TIME {
            get {
                return ResourceManager.GetString("EX_MSG_DATE_START_END_INVALID_SAME_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are registered events for this course.
        /// </summary>
        public static string EX_MSG_EVENTS_REGISTERED_FOR_THIS_COURSE {
            get {
                return ResourceManager.GetString("EX_MSG_EVENTS_REGISTERED_FOR_THIS_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1} invalid.
        /// </summary>
        public static string EX_MSG_INVALID_USER {
            get {
                return ResourceManager.GetString("EX_MSG_INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all mandatory fields. The title and location must contain at least 3 characters..
        /// </summary>
        public static string EX_MSG_MODEL_INVALID {
            get {
                return ResourceManager.GetString("EX_MSG_MODEL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found in database.
        /// </summary>
        public static string EX_MSG_NOT_FOUND_DATABASE {
            get {
                return ResourceManager.GetString("EX_MSG_NOT_FOUND_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields, please..
        /// </summary>
        public static string EX_MSG_NULL_ERROR {
            get {
                return ResourceManager.GetString("EX_MSG_NULL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already registered..
        /// </summary>
        public static string EX_MSG_USER_EXIST {
            get {
                return ResourceManager.GetString("EX_MSG_USER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not enrolled in any course.
        /// </summary>
        public static string EX_MSG_USER_NOT_ENROLLMENT_COURSE {
            get {
                return ResourceManager.GetString("EX_MSG_USER_NOT_ENROLLMENT_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string EX_MSG_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("EX_MSG_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EduPlaner is your tool to maximize academic success! With an innovative approach, our app allows students to access and view their activities and assignments related to each course. Simplifying academic management, EduPlaner helps you stay in control of your studies, ensuring that no important deadlines are missed. Experience the efficiency of an activity manager designed to enhance your educational experience. Discover the power of organization with EduPlaner!.
        /// </summary>
        public static string GENERAL_MSG_DESCRIPTION_PROJECT {
            get {
                return ResourceManager.GetString("GENERAL_MSG_DESCRIPTION_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stay up to date with events and activities, please choose the course in which you are currently enrolled. This will allow you to keep track of all relevant information and participate in scheduled activities. we are here for ensure that you are always well informed and engaged in your course..
        /// </summary>
        public static string GENERAL_MSG_HOME_ENROLLMENT {
            get {
                return ResourceManager.GetString("GENERAL_MSG_HOME_ENROLLMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is mandatory..
        /// </summary>
        public static string GENERAL_MSG_MANDATORY {
            get {
                return ResourceManager.GetString("GENERAL_MSG_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string GENERAL_PAGE_BTN_ADD {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string GENERAL_PAGE_BTN_DETAIL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GENERAL_PAGE_BTN_EDIT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment.
        /// </summary>
        public static string GENERAL_PAGE_BTN_ENROLLMENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_ENROLLMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GENERAL_PAGE_BTN_SAVE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string GENERAL_PAGE_BTN_SHARED {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image perfil.
        /// </summary>
        public static string GENERAL_PAGE_IMAGE_PERFIL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_IMAGE_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CANCEL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CHANGES {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your course.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CHOOSE_COURSE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CHOOSE_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CLOSE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string GENERAL_PAGE_LBL_COURSE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GENERAL_PAGE_LBL_DELETE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this?.
        /// </summary>
        public static string GENERAL_PAGE_LBL_DELETE_THIS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_DELETE_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string GENERAL_PAGE_LBL_EVENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string GENERAL_PAGE_LBL_EVENTS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found, enjoy your day!.
        /// </summary>
        public static string GENERAL_PAGE_LBL_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string GENERAL_PAGE_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string GENERAL_PAGE_LBL_REMOVE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared event.
        /// </summary>
        public static string GENERAL_PAGE_LBL_SHARED_EVENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_SHARED_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TO_THE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TO_THE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TODAY {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TOMORROW {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TOMORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string GENERAL_PAGE_LBL_USER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string GENERAL_PAGE_LINK_IN {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LINK_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GENERAL_PAGE_LINK_OTHER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LINK_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0} created success.
        /// </summary>
        public static string GENERAL_PAGE_MSG__CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG__CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted success.
        /// </summary>
        public static string GENERAL_PAGE_MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} update success.
        /// </summary>
        public static string GENERAL_PAGE_MSG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EduPlaner - Organizing Your Academic Success.
        /// </summary>
        public static string GENERAL_PAGE_TITLE_PROJECT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_TITLE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EduPlaner.
        /// </summary>
        public static string GENERAL_PAGE_WELCOME_EDU_PLANER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_WELCOME_EDU_PLANER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string GENERAL_PRT_LBL_ID {
            get {
                return ResourceManager.GetString("GENERAL_PRT_LBL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your tasks for today and tomorrow..
        /// </summary>
        public static string MSG_PAGE_DASHBOARD_INFO_TASK {
            get {
                return ResourceManager.GetString("MSG_PAGE_DASHBOARD_INFO_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stay up to date with events and activities, please choose the course in which you are currently enrolled. This will allow you to keep track of all relevant information and participate in scheduled activities. we are here for ensure that you are always well informed and engaged in your course..
        /// </summary>
        public static string MSG_PAGE_ENROLLMENT_COURSE {
            get {
                return ResourceManager.GetString("MSG_PAGE_ENROLLMENT_COURSE", resourceCulture);
            }
        }
    }
}
